### PR TITLE
fix: subfolder not found (better then upio check)

### PR DESCRIPTION
**Pull request by rbxlscripts**

### CODE REVIEW

**Review by notpoiu — CHANGES_REQUESTED** [review]
omg bro line 248 line 248line 248line 248line 248line 248line 248line 248line 248line 248line 248line 248line 248line 248line 248line 248line 248line 248line 248line 248line 248line 248line 248line 248

**Comment by notpoiu** [comment]
"better than upio check" :content:

**Review by notpoiu — APPROVED** [review]
finally bro line 248 :content: LGTM

**Comment by rbxlscripts** [comment]
GET OUT-

**Pull request merged**
